// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKHkfXT0fg8hd1t5PJsn8DizbC4uq8EI',
    appId: '1:264272357870:web:6f440a6ceef6597f3e06ff',
    messagingSenderId: '264272357870',
    projectId: 'smartstock-4ea6e',
    authDomain: 'smartstock-4ea6e.firebaseapp.com',
    storageBucket: 'smartstock-4ea6e.firebasestorage.app',
    measurementId: 'G-79Q976M3G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH32zwOPRKgGPTWhVMDA3xl8olq1prnt4',
    appId: '1:264272357870:android:d40824bb9a9462a53e06ff',
    messagingSenderId: '264272357870',
    projectId: 'smartstock-4ea6e',
    storageBucket: 'smartstock-4ea6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9WyyVtLKl27Zz77NUwrHWhGRROgkeUqI',
    appId: '1:264272357870:ios:218c895364946d463e06ff',
    messagingSenderId: '264272357870',
    projectId: 'smartstock-4ea6e',
    storageBucket: 'smartstock-4ea6e.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9WyyVtLKl27Zz77NUwrHWhGRROgkeUqI',
    appId: '1:264272357870:ios:218c895364946d463e06ff',
    messagingSenderId: '264272357870',
    projectId: 'smartstock-4ea6e',
    storageBucket: 'smartstock-4ea6e.firebasestorage.app',
    iosBundleId: 'com.example.smartstock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRKHkfXT0fg8hd1t5PJsn8DizbC4uq8EI',
    appId: '1:264272357870:web:a94b024c58804ff53e06ff',
    messagingSenderId: '264272357870',
    projectId: 'smartstock-4ea6e',
    authDomain: 'smartstock-4ea6e.firebaseapp.com',
    storageBucket: 'smartstock-4ea6e.firebasestorage.app',
    measurementId: 'G-6W2BL76ZQM',
  );
}
